#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Sep 29 13:49:44 EDT 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto a133ba8e278e43108b00edb4684ef17a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot silly_func_self_smart_tb_behav xil_defaultlib.silly_func_self_smart_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto a133ba8e278e43108b00edb4684ef17a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot silly_func_self_smart_tb_behav xil_defaultlib.silly_func_self_smart_tb xil_defaultlib.glbl -log elaborate.log

